services:
  - type: web
    name: modula-backend
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: "pip install --upgrade pip && pip install --index-url https://pypi.org/simple -r requirements.txt"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_REGION
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false